### ISSUE TITLE
Sending voice message at nighttime crashes the app

### ISSUE THREAD

**Issue by SixFive7** [Joolee/nl.joolee.homey.sms#2]
Hi,

For some unknown reason sending a voice message at night causes the app to crash. Messagebird receives the request but logs the voice message status as "not delivered". Maybe they lock it down during the night, i don't know, I'll call them to ask. But more important, this also crashes the app, making all future calls impossible.
Since I'm trying to build a keyfob panic button for when my grandmother has issues, sending messages at night time is a requirement. Anything I can do to help debug this appcrash on my end? I already sent some crashlogs. The latest of which has this ID: c58ecbb0-fc09-4f50-9f4a-7a6d632fd626

Kind regards

**Comment by SixFive7** [comment]
There was indeed an outage. However, during the outage and also right now I still can crash the app. I just send another log: 5b019a60-b765-4fe4-9adf-7851b1cc2e45
Anything else I can do to help debug?

**Comment by Joolee** [comment]
I received the logs. Last one read:

```
A crash occurred for your app (version 1.0.1) at Apr 10, 2018 4:11 PM (UTC).

Homey software version: 1.5.8

Crash report:

    
Note: this log has been manually submitted by a user.
Log ID: 5b019a60-b765-4fe4-9adf-7851b1cc2e45


---- stdout ----
MessageBird API Key: <<removed>>
Registering webhook <<removed>>
<<removed>>
Webhook registered? <<removed>>null true
Balance:  { payment: 'prepaid', type: 'euros', amount: <<removed>> } null
Webhook triggered.  Err:  undefined Args:  { body: {},
  query: 
   { homey: '<<removed>>',
     id: '<<removed>>',
     mccmnc: '20416',
     ported: '0',
     recipient: '<<removed>>',
     reference: 'Homey',
     status: 'answered',
     statusDatetime: '2018-04-10T16:09:22+00:00' },
  headers: 
   { 'accept-encoding': 'gzip',
     'x-forwarded-port': '443',
     'x-forwarded-proto': 'https' } }
Recieved status report. Report: { homey: '<<removed>>',
  id: '<<removed>>',
  mccmnc: '20416',
  ported: '0',
  recipient: '<<removed>>',
  reference: 'Homey',
  status: 'answered',
  statusDatetime: '2018-04-10T16:09:22+00:00' } Stored message: {"id":"<<removed>>","href":"https://rest.messagebird.com/voicemessages/<<removed>>","originator":"inbox","body":"<<removed>>","reference":"Homey","language":"en-gb","voice":"female","repeat":1,"ifMachine":"delay","machineTimeout":7000,"scheduledDatetime":null,"createdDatetime":"2018-04-10T16:07:22+00:00","recipients":{"totalCount":1,"totalSentCount":1,"totalDeliveredCount":0,"totalDeliveryFailedCount":0,"items":[{"recipient":<<removed>>,"status":"calling","statusDatetime":"2018-04-10T16:07:22+00:00"}]},"type":"voice"}

---- stderr ----
TypeError: Cannot read property 'originator' of null
    at /app.js:245:39
    at doCallback (/node_modules/messagebird/lib/messagebird.js:57:9)
    at IncomingMessage.<anonymous> (/node_modules/messagebird/lib/messagebird.js:142:9)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  
```

For some reason, the ``messagebird.messages.read`` requests returns an empty response. Unfortunately, I don't output the err variable to stdout so I can't make a pretty fix. I can, however just ignore that piece of code when it fails, it doesn't really do much important. :)
I'll fix and upload a new version tomorrow.

**Comment by SixFive7** [comment]
Awesome! Thanks :-)

**Comment by Joolee** [comment]
I couldn't replicate the error so I added some simple code to just ignore it. Submitted the app to Athom, I don't know how long it will take.

**Comment by SixFive7** [comment]
Hi,

Thank you for fixing the issue. However, Athom has not yet updated the app. Did something go wrong with the submission? It has been a while and the update is still not available...

Either way, thanks for the effort so far!

**Comment by SixFive7** [comment]
@Joolee 
Hi,

Thank you for fixing the issue. However, Athom has not yet updated the app. Did something go wrong with the submission? It has been a while and the update is still not available...

Either way, thanks for the effort so far!
